// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Training
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject trainingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Training";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		StartDate("StartDate"),
		EndDate("EndDate"),
		Training_Course("MyFirstModule.Training_Course"),
		Training_Location("MyFirstModule.Training_Location"),
		Training_Teacher("MyFirstModule.Training_Teacher");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Training(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Training(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject trainingMendixObject)
	{
		if (trainingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, trainingMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.trainingMendixObject = trainingMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Training.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.Training initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.Training.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Training initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Training(context, mendixObject);
	}

	public static myfirstmodule.proxies.Training load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Training.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Training> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Training.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate()
	{
		return getStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDate
	 */
	public final java.util.Date getStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDate.toString());
	}

	/**
	 * Set value of StartDate
	 * @param startdate
	 */
	public final void setStartDate(java.util.Date startdate)
	{
		setStartDate(getContext(), startdate);
	}

	/**
	 * Set value of StartDate
	 * @param context
	 * @param startdate
	 */
	public final void setStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdate)
	{
		getMendixObject().setValue(context, MemberNames.StartDate.toString(), startdate);
	}

	/**
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate()
	{
		return getEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDate
	 */
	public final java.util.Date getEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDate.toString());
	}

	/**
	 * Set value of EndDate
	 * @param enddate
	 */
	public final void setEndDate(java.util.Date enddate)
	{
		setEndDate(getContext(), enddate);
	}

	/**
	 * Set value of EndDate
	 * @param context
	 * @param enddate
	 */
	public final void setEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddate)
	{
		getMendixObject().setValue(context, MemberNames.EndDate.toString(), enddate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Training_Course
	 */
	public final myfirstmodule.proxies.Course getTraining_Course() throws com.mendix.core.CoreException
	{
		return getTraining_Course(getContext());
	}

	/**
	 * @param context
	 * @return value of Training_Course
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Course getTraining_Course(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Course result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Training_Course.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Course.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Training_Course
	 * @param training_course
	 */
	public final void setTraining_Course(myfirstmodule.proxies.Course training_course)
	{
		setTraining_Course(getContext(), training_course);
	}

	/**
	 * Set value of Training_Course
	 * @param context
	 * @param training_course
	 */
	public final void setTraining_Course(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Course training_course)
	{
		if (training_course == null) {
			getMendixObject().setValue(context, MemberNames.Training_Course.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Training_Course.toString(), training_course.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Training_Location
	 */
	public final myfirstmodule.proxies.Location getTraining_Location() throws com.mendix.core.CoreException
	{
		return getTraining_Location(getContext());
	}

	/**
	 * @param context
	 * @return value of Training_Location
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Location getTraining_Location(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Location result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Training_Location.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Location.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Training_Location
	 * @param training_location
	 */
	public final void setTraining_Location(myfirstmodule.proxies.Location training_location)
	{
		setTraining_Location(getContext(), training_location);
	}

	/**
	 * Set value of Training_Location
	 * @param context
	 * @param training_location
	 */
	public final void setTraining_Location(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Location training_location)
	{
		if (training_location == null) {
			getMendixObject().setValue(context, MemberNames.Training_Location.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Training_Location.toString(), training_location.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Training_Teacher
	 */
	public final myfirstmodule.proxies.Teacher getTraining_Teacher() throws com.mendix.core.CoreException
	{
		return getTraining_Teacher(getContext());
	}

	/**
	 * @param context
	 * @return value of Training_Teacher
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Teacher getTraining_Teacher(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Teacher result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Training_Teacher.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Teacher.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Training_Teacher
	 * @param training_teacher
	 */
	public final void setTraining_Teacher(myfirstmodule.proxies.Teacher training_teacher)
	{
		setTraining_Teacher(getContext(), training_teacher);
	}

	/**
	 * Set value of Training_Teacher
	 * @param context
	 * @param training_teacher
	 */
	public final void setTraining_Teacher(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Teacher training_teacher)
	{
		if (training_teacher == null) {
			getMendixObject().setValue(context, MemberNames.Training_Teacher.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Training_Teacher.toString(), training_teacher.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return trainingMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Training that = (myfirstmodule.proxies.Training) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
